server:
  port: 9999
spring:
  application:
    name: shiro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatisconfig.xml
